"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils import timezone

import socket

import json



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = str(Path(__file__).resolve().parent.parent)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4!qf!8%y5=6ny_01gbgw_wcfb=6+czumg&ig5*$m-2ok@*s=3*'

# SECURITY WARNING: don't run with debug turned on in production!



# Load from a file
with open("env.json", "r") as f:
    env = json.load(f)
DOMAIN = env["domain"]



if DOMAIN != "localhost":
    DEBUG = False
    ALLOWED_HOSTS = ['minhthienk.pythonanywhere.com', 'tinnghiaxuyenmoc.com', 'www.tinnghiaxuyenmoc.com',
    'quanly.tinnghiaxuyenmoc.com']

else:
    DEBUG = True
    ALLOWED_HOSTS = ['minhthienk.pythonanywhere.com', 'localhost','*']

# Version to reload static files
STATIC_VERSION = timezone.now().strftime("%Y%m%d%H%M%S")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_accounts',
    'app_dashboard',
    'widget_tweaks',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'app_dashboard.context_processors.custom_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
computer_name = socket.gethostname()
if DOMAIN != "localhost":
    # use mysql if not local host
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env['database_name'],
            'USER': env['database_user'],
            'PASSWORD': env['database_password'],
            'HOST': env['database_host'],
            'PORT': '3306',
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env['database_name'],
            'USER': env['database_user'],
            'PASSWORD': env['database_password'],
            'HOST': env['database_host'],
            'PORT': '3306',
            'OPTIONS': {
                'charset': 'utf8mb4',             # Hỗ trợ tiếng Việt và emoji
            },
        }
    }
    # use sqlite if local host
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #     }
    # }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Ho_Chi_Minh' 
USE_TZ = False


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

LOGIN_URL = '/account/login/' # replace 'login' with the name of your login view if different


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024  # 5MB


# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "ERROR",  # Only log errors and above
#             "class": "logging.FileHandler",
#             "filename": "django_errors.log",
#             "formatter": "verbose",
#         },
#         "console": {
#             "level": "ERROR",
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#         },
#     },
#     "formatters": {
#         "verbose": {
#             "format": "{levelname} {asctime} {module} {message}",
#             "style": "{",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["file", "console"],
#             "level": "ERROR",  # Show only errors and above
#             "propagate": True,
#         },
#         "django.request": {
#             "handlers": ["file", "console"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#         "django.server": {
#             "handlers": ["file", "console"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#     },
# }
